version: '3'

services:
  backend:
    container_name: backend
    image: backend:latest
    env_file:
      - .env
    build:
      context: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - backend-network
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: frontend
    networks:
      - frontend-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - backend-network
      - frontend-network
    restart: unless-stopped

networks:
  backend-network:
  frontend-network:
